import type { Metadata } from 'next';
import './globals.css';
import { Providers } from '@/components/providers';
import { getIamAuthContext } from '@/iam/utils/get-auth-context';
import { AuthStoreProvider } from '@/stores/auth-store-provider';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/sidebar/app-sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await getIamAuthContext();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Providers>
          <AuthStoreProvider initialAuth={auth}>
            <SidebarProvider>
              <AppSidebar />
              {children}
            </SidebarProvider>
          </AuthStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
